Simplify local development
nstapelbroek/should-i-read-this pull request #1
Opened 2017-06-05 20:20 UTC by nstapelbroek

Hey :raising_hand_man: 

This setup should allow anyone to develop on their local machine without using a "hosted" environment.
Could you take a look and see if this works on your machine?

### What has been changed:
- Added an attempt to handle SIGINT better, since this produces problems on a non-interactive container (It has something to do with `/bin/sh -C`  as CMD and node running on PID 1. I'm not entirely sure what causes this behavior though)
- Installed nodemon to restart the application when developing
- Created a docker-compose file so you can easely develop locally using ngrok and the application code in a mount. 

### How to test:
- Follow the readme :smile:

2017-06-06 20:21 UTC, daanpeer requested changes
For some reason I get a 502. It looks like the application hostname cannot be found from Ngrok. Do you know how we can resolve this?

2017-06-06 20:21 UTC, daanpeer commented on docker-compose.yml
> +          RAZOR_API_KEY: pleasechangeme
Maybe we can use the .env for the razor key :) 

https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

2017-06-06 20:21 UTC, daanpeer commented on README.MD
> +5. Make sure your configure your "Event Subscriptions" in the Slack applicaiton. Currently, the should I read this application requires at least [link_shared](https://api.slack.com/events/link_shared
applicaiton = application 😛

2017-06-06 20:21 UTC, daanpeer commented on src/helpers/signalHandler.js
> +module.exports = signalHandler;
Missing newline

2017-06-06 20:21 UTC, daanpeer commented on README.MD
> +Lateron, you can pull the image from your custom registry and host it just like the "Deployment" describes.
Just a space here

2017-06-07 05:59 UTC, nstapelbroek commented on docker-compose.yml
> +          RAZOR_API_KEY: pleasechangeme
oh sweet! didn't know docker-compose supported a .env file. I'll create a .env.dist and ignore a .env which will be used in the docker-compose :+1:

2017-06-07 06:17 UTC, nstapelbroek commented
@daanpeer Thanks for the feedback :beers: .
I've updated the PR

2017-06-08 06:16 UTC, daanpeer commented on package.json
> +    "watch": "./node_modules/nodemon/bin/nodemon.js -L index.js"
You can just use `nodemon -L index.js` node will use the local node_modules first :)

2017-06-08 06:18 UTC, daanpeer commented
The issue probably has to do with the node_env (nodemon isn't starting ;)) should be an easy fix

2017-06-08 07:10 UTC, daanpeer commented
It does work 🎉

2017-06-08 20:18 UTC, nstapelbroek commented
@daanpeer did changing the `nodemon` fix the entire setup? if so: I've pushed your requested change, lets merge!

2017-06-09 05:51 UTC, merged